export enum AnimalType {
  WHITESHARK = 'WHITESHARK',
  TURTLE = 'TURTLE',
  LOBSTER ='LOBSTER',
  BELUGA = 'BELUGA',
  BOB = 'BOB',
  BOWHEAD = 'BOWHEAD',
  CAPIBARA = 'CAPIBARA',
  GARNELA = 'GARNELA',
  GOMBHAL = 'GOMBHAL',
  IJHAL = 'IJHAL',
  MANATE = 'MANATE',
  ORCA = 'ORCA',
  PANGOLNA = 'PANGOLNA',
  PDOLPHIN = 'PDOLPHIN',
  CUCUMBER = 'CUCUMBER',
  VAMPIRTH = 'VAMPIRTH'
}
