export enum Crewname {
  CAPTAIN = 'CAPTAIN',
  KWAZII = 'KWAZII',
  PESO = 'PESO',
  DASHY = 'DASHY',
  PROFESSOR = 'PROFESSOR',
  SHELLINGTON = 'SHELLINGTON',
  TWEAK = 'TWEAK',
  TUNIP = 'TUNIP',
  BARROT = 'BARROT',
  TUMINOW = 'TUMINOW',
  HALIBEET = 'HALIBEET'

}
